model:
  in_feat: 39
  hid_feat: 32

dataset:
  root_dir: '/data22/tb5zhh/datasets/SemanticKITTI/sequences'
  prefix: cylindrical_less_reflect_ref_pls
  label_directory: scribbles
  spatial_shape: [480,360,32]
  max_bound: [50,3.1415926,2]
  min_bound: [0,-3.1415926,-4]
  aug:
    student: ['rotate', 'flip', 'scale', 'noise']
    teacher: ['rotate', 'flip']
  bin_size: [[24,9],[48,18],[96,36]]
  # LESS_target_diretory: 'LESS_230804_weak_ground_fixed'
  LESS_target_diretory: 'LESS_230810_add_z_sort'


val_dataset:
  root_dir: '/data22/tb5zhh/datasets/SemanticKITTI/sequences'
  prefix: reflec_refpls_cylindrical_mt
  label_directory: labels
  spatial_shape: [480,360,32] 
  max_bound: [50,3.1415926,2]
  min_bound: [0,-3.1415926,-4]
  bin_size: [[24,9],[48,18],[96,36]]
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 9
    - 10
  valid:
    - 8
  test:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
# train_dataloader:
#   batch_size: 2
#   shuffle: True
#   num_workers: 8


train_dataloader:
  batch_size: 2
  shuffle: True
  num_workers: 8

val_dataloader:
  batch_size: 2
  shuffle: False
  num_workers: 8

test_dataloader:
  batch_size: 1
  shuffle: False
  num_workers: 4

trainer:
  max_epochs: 75
  # gpus: [7]
  gpus: -1
  check_val_every_n_epoch: 1
  default_root_dir: 'output'
  accelerator: 'ddp'
  sync_batchnorm: True
  accumulate_grad_batches: 1
  num_sanity_val_steps: 1
# load_checkpoint: '/home/yujc/scribble/scribblekitti/output/scribblekitti_yjc/cylinder3d_mt_LESS/20230727-09:37:07/ckpt/epoch=5-val_teacher_miou=55.46.ckpt'
# load_checkpoint: '/home/yujc/scribble/scribblekitti/output/scribblekitti_yjc/cylinder3d_mt_LESS/20230727-15:51:10/ckpt/epoch=3-val_teacher_miou=55.09.ckpt'
# load_checkpoint: '/home/yujc/scribble/scribblekitti/output/scribblekitti_LESS/cylinder3d_mt_LESS/20230730-21:15:54/ckpt/epoch=13-val_teacher_miou=58.99.ckpt'
# load_checkpoint: '/home/yujc/scribble/scribblekitti/output/scribblekitti_LESS/cylinder3d_mt_LESS/20230802-11:31:51/ckpt/epoch=4-val_teacher_miou=57.18.ckpt'
# load_checkpoint: '/home/yujc/scribble/scribblekitti/output/scribblekitti_LESS/cylinder3d_mt_LESS/20230816-07:21:23/ckpt/epoch=11-val_best_miou=60.41.ckpt'
Weighted_focal_loss:
  alpha: 1
  gamma: 1


# Propogated_Ignore_Index: [9, 11, 15, 17, 18, 19]  # 804
# Propogated_Ignore_Index: [10, 17, 19]  # 810
Propogated_Ignore_Index: []  # 810
drop_percent: 0   # the percent of random drop points which don't calculate loss.


optimizer:
  lr: 0.001

logger:
  project: 'scribblekitti_LESS'
  name: 'weak_label_add_in_train'

Mean_Teacher:
  alpha: 0.99      # Origin is 0.99
