model:
  in_feat: 9
  hid_feat: 32

pretrain_loss: 
  type: barlow_twins
  coef: 0.001

dataset:
  root_dir: '/data22/tb5zhh/datasets/SemanticKITTI/sequences'
  prefix: cylindrical_cluster
  spatial_shape: [480,360,32]
  max_bound: [50,3.1415926,2]
  min_bound: [0,-3.1415926,-4]
  aug: ['rotate', 'flip', 'noise']
  # aug: ['rotate', 'flip', 'scale', 'noise']
  # aug: ['rotate', 'flip']
  bin_size: [[24,9],[48,18],[96,36]]

val_dataset:
  root_dir: '/data22/tb5zhh/datasets/SemanticKITTI/sequences'
  prefix: cylindrical_sample
  spatial_shape: [480,360,32]
  max_bound: [50,3.1415926,2]
  min_bound: [0,-3.1415926,-4]
  aug: []
  bin_size: [[24,9],[48,18],[96,36]]

train_dataloader:
  batch_size: 4
  shuffle: True
  num_workers: 8

val_dataloader:
  batch_size: 1
  shuffle: False
  num_workers: 4

trainer:
  max_epochs: 10
  gpus: -1
  check_val_every_n_epoch: 1
  default_root_dir: '/DATA_EDS2/zhangyk2306'
  accelerator: 'ddp'
  sync_batchnorm: True
  accumulate_grad_batches: 1
  num_sanity_val_steps: 10

load_checkpoint: /DATA_EDS2/zhangyk2306/scribblekitti_tbw/pretrain_bt_cluster/20230830-23:48:44/model/4.ckpt

optimizer:
  lr: 0.001

logger:
  project: 'scribblekitti_tbw'
  name: placeholder # `name` has no effect
