model:
  in_feat: 9
  hid_feat: 32

dataset:
  root_dir: '/home/tb5zhh/workspace/datasets/SemanticKITTI/sequences'
  prefix: cylindrical_mt
  label_directory: scribbles
  spatial_shape: [480,360,32]
  max_bound: [50,3.1415926,2]
  min_bound: [0,-3.1415926,-4]
  aug:
    student: ['rotate', 'flip', 'scale', 'noise']
    teacher: ['rotate', 'flip']
  bin_size: [[24,9],[48,18],[96,36]]

val_dataset:
  root_dir: '/home/tb5zhh/workspace/datasets/SemanticKITTI/sequences'
  prefix: cylindrical_mt
  label_directory: labels
  spatial_shape: [480,360,32]
  max_bound: [50,3.1415926,2]
  min_bound: [0,-3.1415926,-4]
  bin_size: [[24,9],[48,18],[96,36]]

train_dataloader:
  batch_size: 2
  shuffle: True
  num_workers: 8
  drop_last: True

val_dataloader:
  batch_size: 2
  shuffle: False
  num_workers: 8

test_dataloader:
  batch_size: 1
  shuffle: False
  num_workers: 4

trainer:
  max_epochs: 5_
  gpus: -1
  check_val_every_n_epoch: 1
  default_root_dir: "/DATA_EDS2/zhangyk2306"
  accelerator: 'ddp'
  sync_batchnorm: True
  accumulate_grad_batches: 2
  num_sanity_val_steps: 1

load_checkpoint: "/DATA_EDS2/zhangyk2306/scribblekitti_tbw/pretrain_bt_mec/20230725-10:39:27/model/21.ckpt"

optimizer:
  lr: 0.001

logger:
  project: 'linear_finetune'
  name: 'placeholder'
