model:
  in_feat: 9
  hid_feat: 32

dataset:
  root_dir: '/data22/tb5zhh/datasets/SemanticKITTI/sequences'
  prefix: 'cylindrical'
  spatial_shape: [480,360,32]
  max_bound: [50,3.1415926,2]
  min_bound: [0,-3.1415926,-4]
  aug: ['rotate', 'flip', 'noise']
  bin_size: [[24,9],[48,18],[96,36]]

val_dataset:
  root_dir: '/data22/tb5zhh/datasets/SemanticKITTI/sequences'
  prefix: cylindrical
  spatial_shape: [480,360,32]
  max_bound: [50,3.1415926,2]
  min_bound: [0,-3.1415926,-4]
  aug: []
  bin_size: [[24,9],[48,18],[96,36]]

train_dataloader:
  batch_size: 1
  shuffle: True
  num_workers: 16

val_dataloader:
  batch_size: 1
  shuffle: False
  num_workers: 16

trainer:
  max_epochs: 75
  gpus: [0,2,3,7]
  check_val_every_n_epoch: 1
  default_root_dir: 'output'
  accelerator: 'ddp'
  sync_batchnorm: True
  accumulate_grad_batches: 1
  num_sanity_val_steps: 1

optimizer:
  lr: 0.01

logger:
  project: 'scribblekitti'
  name: 'pretraining'
